---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-meteor-zone-v1alpha1-customnbimage
  failurePolicy: Fail
  name: mcustomnbimage.kb.io
  rules:
  - apiGroups:
    - meteor.zone
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - customnbimages
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-meteor-zone-v1alpha1-customnbimage
  failurePolicy: Fail
  name: vcustomnbimage.kb.io
  rules:
  - apiGroups:
    - meteor.zone
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - customnbimages
  sideEffects: None
