# permissions for end users to view customruntimeenvironment.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: customruntimeenvironment-viewer-role
rules:
  - apiGroups:
      - meteor.zone
    resources:
      - customruntimeenvironments
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - meteor.zone
    resources:
      - customruntimeenvironments/status
    verbs:
      - get
