# permissions for end users to edit customruntimeenvironment.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: customruntimeenvironment-editor-role
rules:
  - apiGroups:
      - meteor.zone
    resources:
      - customruntimeenvironments
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - meteor.zone
    resources:
      - customruntimeenvironments/status
    verbs:
      - get
